apiVersion: batch/v1
kind: Job
metadata:
  generateName: testjob
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: busybox
        command:
          - "/bin/sh"
          - "-c"
          - "echo ok" 
      restartPolicy: Never
  backoffLimit: 2
  ttlSecondsAfterFinished: 120
